// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyL5xBrqTmAt2KOUD9OsjSbrMfKMLbV-w',
    appId: '1:743000414425:web:933ac84dcc695d62c706c8',
    messagingSenderId: '743000414425',
    projectId: 'bama-events',
    authDomain: 'bama-events.firebaseapp.com',
    storageBucket: 'bama-events.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh4OOH_9fsG4gNz2eiQ9GAxEXWrcWRzOU',
    appId: '1:743000414425:android:3094465c8fbb8c1cc706c8',
    messagingSenderId: '743000414425',
    projectId: 'bama-events',
    storageBucket: 'bama-events.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALz9BqJ7tpZ_JUDVikh_muWMrnmoVIigs',
    appId: '1:743000414425:ios:9de0d45c92582541c706c8',
    messagingSenderId: '743000414425',
    projectId: 'bama-events',
    storageBucket: 'bama-events.firebasestorage.app',
    iosBundleId: 'com.example.bama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALz9BqJ7tpZ_JUDVikh_muWMrnmoVIigs',
    appId: '1:743000414425:ios:9de0d45c92582541c706c8',
    messagingSenderId: '743000414425',
    projectId: 'bama-events',
    storageBucket: 'bama-events.firebasestorage.app',
    iosBundleId: 'com.example.bama',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyL5xBrqTmAt2KOUD9OsjSbrMfKMLbV-w',
    appId: '1:743000414425:web:cac98cb826c8ddefc706c8',
    messagingSenderId: '743000414425',
    projectId: 'bama-events',
    authDomain: 'bama-events.firebaseapp.com',
    storageBucket: 'bama-events.firebasestorage.app',
  );
}
